#ifndef TIMER_H
#define TIMER_H

// Timer defs
#define TM_ZERO                         0
#define TM_RESET_STATIC_VARS            30
#define TM_END_POP_MENU_ANIM            13
#define TM_START_ROUND_END_REWARDS_ANIM 1
#define TM_END_DISPLAY_FIN_BLIND        30
#define TM_END_DISPLAY_SCORE_MIN        4
#define TM_REWARDS_ELLIPSIS_PRINT_START 2
#define TM_REWARDS_ELLIPSIS_PRINT_END   16
#define TM_REWARD_DISPLAY_INTERVAL      15
#define TM_DISPLAY_REWARDS_CONT_WAIT    (TM_REWARDS_ELLIPSIS_PRINT_END + TM_REWARD_DISPLAY_INTERVAL)
#define TM_HAND_REWARD_INCR_WAIT        (TM_DISPLAY_REWARDS_CONT_WAIT + TM_REWARD_DISPLAY_INTERVAL)
#define TM_REWARD_INCREMENT_INTERVAL    20
#define TM_DISMISS_ROUND_END_TM         20
#define TM_CREATE_SHOP_ITEMS_WAIT       1
#define TM_SHIFT_SHOP_ICON_WAIT         7
#define TM_END_GAME_SHOP_INTRO          12
#define TM_SHOP_PRC_INPUT_START         1
#define TM_BLIND_SELECT_START           1
#define TM_END_ANIM_SEQ                 12
#define TM_DISP_BLIND_PANEL_FINISH      7
#define TM_DISP_BLIND_PANEL_START       1

#endif // TIMER_H
